/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2023-10-15 16:43:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.User.Post;
import java.util.List;
import com.Db.DBConnect;
import com.Dao.PostDao;
import com.User.UserDetails;

public final class showNotes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/all_component/navbar.jsp", Long.valueOf(1691757418672L));
    _jspx_dependants.put("/all_component/allcss.jsp", Long.valueOf(1688132662360L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.User.UserDetails");
    _jspx_imports_classes.add("com.Db.DBConnect");
    _jspx_imports_classes.add("com.User.Post");
    _jspx_imports_classes.add("com.Dao.PostDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	UserDetails user3 = (UserDetails) session.getAttribute("userD");

	if (user3 == null) {
		response.sendRedirect("login.jsp");
		session.setAttribute("login-error", "please login...");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Show Notes</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-custom navbar-custom\">\r\n");
      out.write("\t<a class=\"navbar-brand\" href=\"#\"><i class=\"fa fa-book\"\r\n");
      out.write("\t\taria-hidden=\"true\"></i> ENotes</a>\r\n");
      out.write("\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t</button>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\" href=\"home.jsp\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-home\" aria-hidden=\"true\"></i> Home <span\r\n");
      out.write("\t\t\t\t\tclass=\"sr-only\">(current)</span> </a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"addNotes.jsp\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-plus-circle\" aria-hidden=\"true\"></i> Add Notes</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link \" href=\"showNotes.jsp\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-address-book\" aria-hidden=\"true\"></i> ShowNotes</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t");

			UserDetails us = (UserDetails) session.getAttribute("userD");

			if (us != null) {
		
      out.write("\r\n");
      out.write("\t\t<a href=\"\" class=\"btn btn-light my-2 my-sm-0 mr-2\" data-toggle=\"modal\" data-target=\"#exampleModal\"\r\n");
      out.write("\t\t\ttype=\"submit\"><i class=\"fa fa-user-circle-o\" aria-hidden=\"true\"></i>");
      out.print( us.getName() );
      out.write("</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<a href=\"LogoutServlet\" class=\"btn btn-light my-2 my-sm-0\"\r\n");
      out.write("\t\t\ttype=\"submit\"><i class=\"fa fa-user-plus\" aria-hidden=\"true\"></i>Logout</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Button trigger modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Modal title</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("                             <i class=\"fa fa-user fa-3x\"></i>\r\n");
      out.write("                             <h5></h5>\r\n");
      out.write("                             \r\n");
      out.write("                             <table class=\"table\">\r\n");
      out.write("                             <tbody>\r\n");
      out.write("                                 <tr>\r\n");
      out.write("                                    <th>User Id</th>\r\n");
      out.write("                                    <td>");
      out.print( us.getId() );
      out.write("</td>\r\n");
      out.write("                                 </tr>\r\n");
      out.write("                                 \r\n");
      out.write("                                   <tr>\r\n");
      out.write("                                      <th>Full Name</th>\r\n");
      out.write("                                      <td>");
      out.print( us.getName() );
      out.write("</td>\r\n");
      out.write("                                   </tr>\r\n");
      out.write("                                   \r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                       <th>Email Id</th>\r\n");
      out.write("                                       <td>");
      out.print( us.getEmail() );
      out.write("</td>\r\n");
      out.write("                                   </tr>\r\n");
      out.write("                                  </tbody>\r\n");
      out.write("                                   </table>\r\n");
      out.write("                                   \r\n");
      out.write("                                   <div>\r\n");
      out.write("                                      <button type=\"button\" class=\"btn-btn-primary\"\r\n");
      out.write("                                      data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                  \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");

			} else {
		
      out.write("\r\n");
      out.write("\t\t<a href=\"login.jsp\" class=\"btn btn-light my-2 my-sm-0 mr-2\"\r\n");
      out.write("\t\t\ttype=\"submit\"><i class=\"fa fa-user-circle-o\" aria-hidden=\"true\"></i>login</a>\r\n");
      out.write("\t\t<a href=\"register.jsp\" class=\"btn btn-light my-2 my-sm-0\"\r\n");
      out.write("\t\t\ttype=\"submit\"><i class=\"fa fa-user-plus\" aria-hidden=\"true\"></i>Register</a>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</nav>");
      out.write('\r');
      out.write('\n');
      out.write('	');

		String updateMsg = (String) session.getAttribute("updateMsg");
		if (updateMsg != null) {
	
      out.write("\r\n");
      out.write("     <div class=\"alert alert-success\" role=\"alert\">");
      out.print(updateMsg);
      out.write("</div>\r\n");
      out.write("\t");

	session.removeAttribute("updateMsg");
		}
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		String wrongMsg = (String) session.getAttribute("wrongMsg");
		if (wrongMsg != null) {
	
      out.write("\r\n");
      out.write("     <div class=\"alert alert-danger\" role=\"alert\">");
      out.print(wrongMsg);
      out.write("</div>\r\n");
      out.write("\t");

	session.removeAttribute("wrongMsg");
		}
	
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h2 class=\"text-center\">All Notes:</h2>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t");

					if (user3 != null) {
						PostDao ob = new PostDao(DBConnect.getCOnn());
						List<Post> post = ob.getData(user3.getId());
						for (Post po : post) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"card-mt-3\">\r\n");
      out.write("\t\t\t\t\t<img alt=\"\" src=\"img/paper.png\" class=\"card-img-top mt-2 mx-auto\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"max-width: 100px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body p-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title \">");
      out.print(po.getTitle());
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t\t<p>");
      out.print(po.getContent());
      out.write(".\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<b class=\"text-success\">Published By:");
      out.print(user3.getName());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</b></br> <b class=\"text-primary\"></b>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<b class=\"text-success\">Published Date:");
      out.print(po.getPdate());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</b></br> <b class=\"text-success\"></b>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container text-center mt-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"deleteServlet?note_id=");
      out.print(po.getId() );
      out.write("\" class=\"btn btn-danger\">Delete</a> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"edit.jsp?note_id=");
      out.print(po.getId());
      out.write("\" class=\"btn btn-primary\">Edit</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
